Tarea1/Noticiario/config/routes.rb
Rails.application.routes.draw do
  #resources :comments
  resources :entries do
    resources :comments
  end
  devise_for :admins
  resources :admins do
    resources :entries
  end
  # Editar noticias
  patch '/admins/:admin_id/entries/:id(.:format)/edit', to: 'entries#update'
  #Eliminar noticias
  delete '/admins/:admin_id/entries/:id(.:format)', to: 'entries#destroy'
  root to: "entries#index"
  # Creación de noticias
  #get 'entries/new_entry', to: 'entries#new', :as => :new_entry
  post '/entry_form', to: 'entries#create'
  get '/entry_form', to: 'entries#new', :as => :admin_create_entry
  # Mostrar todas las noticias
  get 'entries', to: 'entries#index'
  # Mostrar una noticias
  get 'entries/:id(.:format)', to: 'entries#show', :as => :show_entry
  # Crear comentarios
  post '/entries/:entry_id/comments(.:format)', to: 'comments#create', :as => :new_entry_comment_post2
  post '/entries/:entry_id/', to: 'comments#create', :as => :new_entry_comment_post
  post '/comments/new', to: 'comments#create'

  get '/transforme', to: 'api/api#hola'
end

Tarea1/Noticiario/app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

Tarea1/Noticiario/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Tarea1/Noticiario/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :entry
end

Tarea1/Noticiario/app/models/entry.rb
class Entry < ApplicationRecord
  has_many :comments
end

Tarea1/Noticiario/app/controllers/api/api_controller.rb
class Api::ApiController < ActionController::API

  def hola
    render json: {'Authorized': params[:code]}, status: 200
  end
end

Tarea1/Noticiario/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Tarea1/Noticiario/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    puts 'ACA'
    puts comment_params[:entry_id]
    puts 'ACA'
    @entry = Entry.find_by_id(params[:entry_id])
    new_hash = {}
    new_hash[:name] = params[:comment][:name]
    new_hash[:content] = params[:comment][:content]
    @entry = @entry.comments.new(new_hash)
    if @entry.save
      redirect_to entry_url(id: params[:entry_id]), notice: 'El comentario ha sido posteado exitosamente!'
    else
      redirect_to entry_url
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:name, :content, :entry_id)
  end
end

Tarea1/Noticiario/app/controllers/entries_controller.rb
class EntriesController < ApplicationController
    #before_action :logged_in?, only: [:create, :destroy]

    #def index
    #  @artists_user = Artist.where(user_id: current_user.id)
    #  @artists = Artist.where.not(user_id: current_user.id)
    #end
    before_action :authenticate_admin!, except: [:index, :show]

    def new
      @entry = Entry.new
    end

    def create
      @entry = Entry.new(entry_params)
      if @entry.save
        flash[:success] = "Noticia agregada!"
        redirect_to entries_url
      end
    end

    def index
      @entries = Entry.all.sort_by{|e| e[:created_at]}.reverse
    end

    def update
      @entry = Entry.find(params[:id])
      if @entry.update_attributes(entry_params)
        flash[:success] = "Noticia actualizada"
        redirect_to entries_url
      else
        flash[:error] = "No ha sido posible actualizar la noticia"
        redirect_to entries_url
      end
    end


    def edit
      @entry = Entry.find(params[:id])
      render 'edit'
    end

    def show
      @entry = Entry.find(params[:id])
      @comments = @entry.comments
      @comment = Comment.new
    end

    def destroy
      @entry = Entry.find(params[:id]).destroy
      if @entry.destroy
        flash[:success] = "Noticia eliminada"
        redirect_to entries_url
      else
        flash[:error] = "No se pudo eliminar la noticia"
        redirect_to entries_url
      end
    end

    private
      def entry_params
        params.require(:entry).permit(:headline, :dropline, :body)
    end
end

Tarea1/Noticiario/app/helpers/application_helper.rb
module ApplicationHelper
end

Tarea1/Noticiario/app/helpers/entries_helper.rb
module EntriesHelper
end

Tarea1/Noticiario/app/views/entries/_admin.html.erb
<head> <br><center> <h1>Administrar Noticias</h1> </center></head>
<body>
  <container>
    <div>
      <u1>
        <% if @entries.nil? %>
          <h3> Sin noticias... </h3>
        <% else %>
            <table>
              <tr>
                <th>Noticia</th>
                <th>Fecha Publicación</th>
                <th>Acciones</th>
              </tr>
              <% @entries.each do |entry| %>
                <tr>
                  <td><%= entry.headline %></td>
                  <td><%= entry.created_at %></td>
                  <td><%= link_to "editar", edit_admin_entry_path(:admin_id => current_admin.id,
                   :id => entry.id) %> | <%= link_to 'eliminar',
                   admin_entry_path(:admin_id => current_admin.id,
                   :id => entry.id), method: :delete,
                    data: { confirm: '¿Estás seguro que quieres eliminar la noticia?' }%> </td>
                </tr>
              <% end %>
            </table>
        <% end %>
      <br><br><br>
      </u1>
      <center><button type="button"><%= link_to "Publicar Noticia", new_entry_path, class: "nounderline", style: 'color:#000000;' %> </button></center>
    </div>
  </container>
</body>

Tarea1/Noticiario/app/views/entries/_no_admin.html.erb
<head> <br><center> <h1>Noticias</h1> </center></head>
<body>
  <container>
    <div>
      <u1>
        <% if @entries.nil? %>
          <h3> Sin noticias... </h3>
        <% elsif @entries.length >= 10 %>
          <% @entries = @entries.first(10) %>
        <% end %>
        <% @entries.each do |entry| %>
            <center><h2> <%= entry.headline %> </h2>
            <h3> <%= entry.dropline %> </h3></center>
            <h5> <%= entry.created_at %> </h5>
            <br>
            <% if entry.body.length > 500 %>
              <h4> <%= entry.body[0..499]+'...' %> </h4>
            <% else %>
              <h4> <%= entry.body %> </h4>
            <% end %>
            <%= link_to "ver", show_entry_path(:id => entry.id) %> | Comentarios: <%= entry.comments.length %>
            <p><%= "-"*250 %></p>
        <% end %>
      </u1>
    </div>
  </container>
</body>

Tarea1/Noticiario/app/views/entries/edit.html.erb
<h1>Editar noticia</h1>
<div class="container">
  <div class="jumbotron">
    <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@entry, url: edit_admin_entry_path) do |f| %>
        <%= f.label :Título_de_la_Noticia %>
        <br/>
        <%= f.text_area :headline, :cols => "100", :rows => "1",
        :maxlength =>"100", :required => 'required', :value => @entry.headline %>
        <br/><br/><br/>
        <%= f.label :Bajada_de_Título %>
        <br/>
        <%= f.text_area :dropline, :cols => "100", :rows => "3",
        :maxlength =>"200", :required => 'required', :value => @entry.dropline %>
        <br/><br/><br/>
        <%= f.label :Cuerpo_de_la_Noticia %>
        <br/>
        <%= f.text_area :body, :cols => "100", :rows => "12",
        :required => 'required' , :value => @entry.body %>
        <br/>
        <p>Fecha publicación: <%= @entry.created_at %> </p>
        <p>Fecha última edición: <%= @entry.updated_at %> </p>
        <br/><br/><br/>
        <%= f.submit "Editar Noticia", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>
</div>

Tarea1/Noticiario/app/views/entries/index.html.erb
<!DOCTYPE html>
<html>
<% if admin_signed_in? %>
  <%= render :file => 'app/views/entries/_admin.html.erb' %>
<% else %>
  <%= render :file => 'app/views/entries/_no_admin.html.erb' %>
<% end %>
<%= @sitio %>
</html>

Tarea1/Noticiario/app/views/entries/new.html.erb
<center>
<h1>Nueva Noticia</h1>
<div class="container">
  <div class="jumbotron">
    <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@entry, url: admin_create_entry_path) do |f| %>
        <%= f.label :Título_de_la_Noticia %>
        <br/>
        <%= f.text_area :headline, :cols => "100", :rows => "1",
        :maxlength =>"100", :required => 'required'%>
        <br/><br/><br/>
        <%= f.label :Bajada_de_Título %>
        <br/>
        <%= f.text_area :dropline, :cols => "100", :rows => "3",
        :maxlength =>"200", :required => 'required' %>
        <br/><br/><br/>
        <%= f.label :Cuerpo_de_la_Noticia %>
        <br/>
        <%= f.text_area :body, :cols => "100", :rows => "12",
        :required => 'required' %>
        <br/><br/><br/>
        <%= f.submit "Ingresar Nueva Noticia", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>
</div>
</center>

Tarea1/Noticiario/app/views/entries/show.html.erb
<center><h1>Noticia</h1></center>
<br><br>
<center><h2><%= @entry.headline %></h2></center>
<br><br>
<center><h3><%= @entry.dropline %></h3></center>
<br>
<h4><%= @entry.created_at %><h4>
<ul>
  <div>
      <p> <%= @entry.body %> </p>
  </div>
</ul>
<br><br><br>
<h1> Comentarios </h1>
<% if @comments.length == 0 %>
  <h3> Sin comentarios... </h3>
<% else %>
  <div>
    <% @comments.each do |comment|%>
      <h3><%= comment.name %> </h3><h5><%= comment.created_at.strftime('Fecha %d/%m/%Y Hora %H:%M hrs') %></h5>
      <center><h4><%= comment.content %></h4></center>
      <br><br>
    <% end %>
  </div>
<% end %>
<br><br><br>
<h1>Agregar Comentario</h1>
<div>
  <div class="container">
    <div class="jumbotron">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= form_for(@comment, url: new_entry_comment_post_path(@entry.id)) do |f| %>
            <%= f.label :Nombre %><br/>
            <%= f.text_area :name, :cols => "50", :rows => "1", :maxlength =>"50", :required => 'required', :value => 'Ingresa acá tu nombre' %><br/><br/><br/>
            <%= f.label :Comentario %><br/>
            <%= f.text_area :content, :cols => "100", :rows => 5, :maxlength =>"500", :required => 'required', :value => 'Ingresa acá tu comentario' %>
            <%= @entry.id %>
            <%= hidden_field_tag 'entry_id', @entry.id %> <br/><br/><br/>
            <%= f.submit "Publicar Comentario", class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

Tarea1/Noticiario/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Noticiario</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <% if admin_signed_in? %>
      <div class="right"><%= link_to('Logout', destroy_admin_session_path, method: :delete, style: 'color:#000000;')%></div>
    <% else %>
      <div class="right"><%= link_to "Administrar", new_admin_session_path , style: 'color:#000000;'%></div>
    <% end %>
    <%= yield %>
  </body>
</html>